app:
  Name: app
  Version: 1.0.0
  PprofPort: :5555
  Mode: debug                 # debug, release, test
  JwtSecret: JWT_SECRET
  JwtTimeout: 86400
  CookieName: jwt-token
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: true

Http:
  Addr: :8080
  ReadTimeout: 5
  WriteTimeout: 5


logger:
  Development: false
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json                          # json or console
  Level: info                             # 日志级别，DEBUG, INFO, WARN, ERROR, FATAL
  Name: app
  Writers: file,console                    # 有2个可选项：file,console 选择file会将日志记录到logger_file指定的日志文件中，选择console会将日志输出到标准输出，当然也可以两者同时选择
  LoggerFile: log/app.log
  LoggerWarnFile: log/app.wf.log
  LoggerErrorFile: log/app.err.log
  LogRollingPolicy: daily
  LogRotateDate: 1
  LogRotateSize: 1
  LogBackupCount: 7

mysql:
  Name: app                     # 数据库名称
  Addr: 192.168.2.175:3306            # 如果是 docker,可以替换为 对应的服务名称，eg: db:3306
  UserName: root
  Password: app
  ShowLog: true                   # 是否打印SQL日志
  MaxIdleConn: 10                 # 最大闲置的连接数，0意味着使用默认的大小2， 小于0表示不使用连接池
  MaxOpenConn: 60                 # 最大打开的连接数, 需要小于数据库配置中的max_connections数
  ConnMaxLifeTime: 60m            # 单个连接最大存活时间，建议设置比数据库超时时长(wait_timeout)稍小一些


website:
  Name: app
  Domain: http://app.com
  Secret: abcdefg
  Static: /data/static